package io.github.miner7222.gap

import java.io.File
import java.util.Locale
import java.util.TreeSet

object SupportedPackageList {

    private const val GENERATED_HEADER = "# Generated by GAP package manager"
    const val ACTIVE_LIST_PATH = "/system/etc/gpp_app_list"
    const val GAME_HELPER_PACKAGE = "com.zui.game.service"
    const val MODULE_ID = "y705-lsr"
    // GAP writes the optional runtime override here. When absent, the device's
    // stock /system/etc/gpp_app_list remains the source of truth.
    const val MODULE_LIST_PATH = "/data/adb/modules/$MODULE_ID/system/etc/gpp_app_list"

    fun readActivePackages(): LinkedHashSet<String> {
        return readPackages(File(ACTIVE_LIST_PATH))
    }

    fun readPackages(file: File): LinkedHashSet<String> {
        if (!file.exists() || !file.canRead()) {
            return LinkedHashSet()
        }

        return parsePackages(file.readText())
    }

    fun parsePackages(rawText: String): LinkedHashSet<String> {
        val packages = LinkedHashSet<String>()
        rawText.lineSequence().forEach { rawLine ->
            val line = rawLine.trim()
            // Keep the file hand-editable: blank lines and comments are ignored.
            if (line.isBlank() || line.startsWith("#")) {
                return@forEach
            }
            packages += line
        }
        return packages
    }

    fun buildFileContents(packages: Collection<String>): String {
        // Stable ordering keeps diffs readable when the file is inspected on-device.
        val normalized = TreeSet(String.CASE_INSENSITIVE_ORDER)
        packages.mapTo(normalized) { it.trim() }

        return buildString {
            appendLine(GENERATED_HEADER)
            appendLine("# One package name per line")
            normalized
                .asSequence()
                .filter { it.isNotBlank() }
                .forEach { appendLine(it) }
        }
    }

    fun normalizeQuery(query: String): String {
        return query.trim().lowercase(Locale.ROOT)
    }
}
