name: Build GAP Debug APK

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '**/*.md'

jobs:
  build:
    name: Build GAP Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21' 

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Fix Line Endings and Grant Execute Permission for Gradlew
        run: |
          sed -i -e 's/\r$//' gradlew
          chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v7
        with:
          name: GAP-Debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 14
